spring:
  application:
    name: muse-ai
  main:
    banner-mode: console  # 显示banner（可选值：console-显示、off-关闭、log-输出到日志）
  banner:
    charset: UTF-8  # banner文件编码
    location: classpath:banner
  datasource:
    url: jdbc:mysql://106.54.215.151:3306/muse_ai
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.minimaxi.com/v1
      api-key: ${MUSE_MINIMAX_API_KEY}
      model-name: MiniMax-M2.5
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      max-retries: 3
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.edu.sxu.museai.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 7777
  servlet:
    context-path: /api
# MinIO配置
minio:
  endpoint: http://106.54.215.151:9000
  access-key: root
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: muse-ai

